### PR TITLE
[WIP] Add support for T20 platform and misc cleanup

### PR DESCRIPTION
**Pull request by bengris32**
This PR adds initial open sdk support for the Ingenic T20 (and T10 too, perhaps). I've only tested this on a T20 board with a jxf23 sensor, will need more varied testing (on both T10 and T20 with other sensors) before merge.

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
Thank you so much for all your hard work. 
Please give a little more explanation where this code came from and what kind of successful changes you managed to achieve in the firmware.

https://t.me/openipc/73091

**Comment by bengris32** [comment]
tx-isp and jxf23 driver: https://s3-us-west-2.amazonaws.com/download.wyzecam.com/firmware/gpl/kernel_modules_wyze_cam_v2_pan.tar.gz
rest of sensor drivers: https://github.com/debugdump/Ingenic-T10_20/blob/master/opensource/drivers.7z

I preferred to use Wyze's tx-isp driver mainly because it seems to be from a later SDK
(H201709151519) that hasn't appeared anywhere yet (from what I could find).
I did do a diff between the tx-isp driver from Wyze and the one from the older SDK
and couldn't really see anything that would cause issues on other boards (hoping that they didn't modify anything).
I'm still unsure about it however (which is another reason to this change more).

Functionality wise, everything is still working with source built modules on my Wyze V2.

**Comment by gtxaspec** [comment]
@bengris32 are you able to allocate more memory to OSMEM? Right now we are at `mem=40M rmem=24M` 
The device has 128M of ram.   stock fw is at `mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000`
 I can't do more than 40M~ otherwise the kernel crashes on boot or majestic crashes the kernel on ISP open.

**Comment by gtxaspec** [comment]
Confirmed this pr works well on the wyze v2 device.

**Comment by gtxaspec** [comment]
@bengris32 any update on this/?  Would love to have all the modules build in openingenic vs using the precompiled binaries =D

**Comment by flyrouter** [comment]
So, what suggestions do you have for this PR, are we closing it as outdated ?

**Comment by gtxaspec** [comment]
I think it's a good addition for t10/t20 device support.  If @bengris32 doesn't have the time to finish the PR I could make a new one as well.  Building the modules from source instead of relying on precompiled binaries is a definite advantage.

**Comment by bengris32** [comment]
Sorry to have kept you all hanging for so long!

@gtxaspec feel free to continue/resubmit the PR (same for anyone else, do whatever you feel like doing with it), it will however need rebasing since I've seen a lot of changes since this was submitted.

**Comment by flyrouter** [comment]
Closed due to creation of a parallel patch thread.

**Pull request closed without merging**
